package com.quran.labs.androidquran.common.ui.core
import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF00696F)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFF79F5FF)
val lightOnPrimaryContainer = Color(0xFF002022)
val lightSecondary = Color(0xFF4A6365)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFCCE8EA)
val lightOnSecondaryContainer = Color(0xFF051F21)
val lightTertiary = Color(0xFF4F5F7D)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFD7E2FF)
val lightOnTertiaryContainer = Color(0xFF0A1B36)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFF4FAFB)
val lightOnBackground = Color(0xFF161D1D)
val lightSurface = Color(0xFFF4FAFB)
val lightOnSurface = Color(0xFF161D1D)
val lightSurfaceVariant = Color(0xFFDAE4E5)
val lightOnSurfaceVariant = Color(0xFF3F4849)
val lightOutline = Color(0xFF6F797A)
val lightOutlineVariant = Color(0xFFBEC8C9)
val lightInverseOnSurface = Color(0xFFECF2F2)
val lightInverseSurface = Color(0xFF2B3232)
val lightInversePrimary = Color(0xFF4DD9E4)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF00696F)
val lightSurfaceDim = Color(0xFFD5DBDB)
val lightSurfaceBright = Color(0xFFF4FAFB)
val lightSurfaceContainerLowest = Color(0xFFFFFFFF)
val lightSurfaceContainerLow = Color(0xFFEFF5F5)
val lightSurfaceContainer = Color(0xFFE9EFEF)
val lightSurfaceContainerHigh = Color(0xFFE3E9EA)
val lightSurfaceColorHighest = Color(0xFFDDE4E4)

val darkPrimary = Color(0xFF4DD9E4)
val darkOnPrimary = Color(0xFF00363A)
val darkPrimaryContainer = Color(0xFF004F54)
val darkOnPrimaryContainer = Color(0xFF79F5FF)
val darkSecondary = Color(0xFFB1CBCE)
val darkOnSecondary = Color(0xFF1B3436)
val darkSecondaryContainer = Color(0xFF324B4D)
val darkOnSecondaryContainer = Color(0xFFCCE8EA)
val darkTertiary = Color(0xFFB7C7EA)
val darkOnTertiary = Color(0xFF21304C)
val darkTertiaryContainer = Color(0xFF374764)
val darkOnTertiaryContainer = Color(0xFFD7E2FF)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF0E1415)
val darkOnBackground = Color(0xFFDDE4E4)
val darkSurface = Color(0xFF0E1415)
val darkOnSurface = Color(0xFFDDE4E4)
val darkSurfaceVariant = Color(0xFF3F4849)
val darkOnSurfaceVariant = Color(0xFFBEC8C9)
val darkOutline = Color(0xFF899393)
val darkOutlineVariant = Color(0xFF3F4849)
val darkInverseOnSurface = Color(0xFF2B3232)
val darkInverseSurface = Color(0xFFDDE4E4)
val darkInversePrimary = Color(0xFF00696F)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFF4DD9E4)
val darkSurfaceDim = Color(0xFF0E1415)
val darkSurfaceBright = Color(0xFF343A3B)
val darkSurfaceContainerLowest = Color(0xFF090F10)
val darkSurfaceContainerLow = Color(0xFF161D1D)
val darkSurfaceContainer = Color(0xFF1A2121)
val darkSurfaceContainerHigh = Color(0xFF252B2C)
val darkSurfaceColorHighest = Color(0xFF303636)

// generated with a seed of #ff1b6b71 (tonal spot, 2021 spec). this is the "original" palette - the
// xml side carries the same values in app/src/main/res/values{,-night}/colors_theme.xml, so keep
// the two in sync.
