package com.quran.labs.androidquran.common.ui.core
import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF006D3E)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFF8CF8B4)
val lightOnPrimaryContainer = Color(0xFF00210F)
val lightSecondary = Color(0xFF516355)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFD4E7D6)
val lightOnSecondaryContainer = Color(0xFF0F1F14)
val lightTertiary = Color(0xFF775A02)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFFFDF98)
val lightOnTertiaryContainer = Color(0xFF251A00)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFF8FAF5)
val lightOnBackground = Color(0xFF191C1A)
val lightSurface = Color(0xFFF8FAF5)
val lightOnSurface = Color(0xFF191C1A)
val lightSurfaceVariant = Color(0xFFDCE5DB)
val lightOnSurfaceVariant = Color(0xFF414942)
val lightOutline = Color(0xFF717971)
val lightOutlineVariant = Color(0xFFC0C9C0)
val lightInverseOnSurface = Color(0xFFF0F1EC)
val lightInverseSurface = Color(0xFF2E312E)
val lightInversePrimary = Color(0xFF6FDC9A)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF006D3E)
val lightSurfaceDim = Color(0xFFD9DBD6)
val lightSurfaceBright = Color(0xFFF8FAF5)
val lightSurfaceContainerLowest = Color(0xFFFFFFFF)
val lightSurfaceContainerLow = Color(0xFFF3F4EF)
val lightSurfaceContainer = Color(0xFFEDEEEA)
val lightSurfaceContainerHigh = Color(0xFFE7E9E4)
val lightSurfaceColorHighest = Color(0xFFE1E3DE)

val darkPrimary = Color(0xFF6FDC9A)
val darkOnPrimary = Color(0xFF00391E)
val darkPrimaryContainer = Color(0xFF00522E)
val darkOnPrimaryContainer = Color(0xFF8CF8B4)
val darkSecondary = Color(0xFFB8CBBB)
val darkOnSecondary = Color(0xFF243429)
val darkSecondaryContainer = Color(0xFF3A4B3E)
val darkOnSecondaryContainer = Color(0xFFD4E7D6)
val darkTertiary = Color(0xFFE8C266)
val darkOnTertiary = Color(0xFF3F2E00)
val darkTertiaryContainer = Color(0xFF5A4300)
val darkOnTertiaryContainer = Color(0xFFFFDF98)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF1B1E1C)
val darkOnBackground = Color(0xFFE1E3DE)
val darkSurface = Color(0xFF1B1E1C)
val darkOnSurface = Color(0xFFE1E3DE)
val darkSurfaceVariant = Color(0xFF414942)
val darkOnSurfaceVariant = Color(0xFFC0C9C0)
val darkOutline = Color(0xFF8A938B)
val darkOutlineVariant = Color(0xFF414942)
val darkInverseOnSurface = Color(0xFF2E312E)
val darkInverseSurface = Color(0xFFE1E3DE)
val darkInversePrimary = Color(0xFF006D3E)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFF6FDC9A)
val darkSurfaceDim = Color(0xFF1B1E1C)
val darkSurfaceBright = Color(0xFF404441)
val darkSurfaceContainerLowest = Color(0xFF161916)
val darkSurfaceContainerLow = Color(0xFF202321)
val darkSurfaceContainer = Color(0xFF252826)
val darkSurfaceContainerHigh = Color(0xFF2F322F)
val darkSurfaceColorHighest = Color(0xFF3A3D3A)

// the "original" palette: an emerald primary with a soft gold tertiary and faintly green neutrals,
// built from the standard Material 3 tone mapping (see the tonal palettes at hue 158 / 88). the xml
// side carries the same values in app/src/main/res/values{,-night}/colors_theme.xml, so keep the
// two in sync.
